import "./globals.css";
import type { Metadata } from "next";
import { useState } from "react";
import { Inter } from "next/font/google";
import { Button, Navbar, MobileNav, Typography, IconButton } from "./mui";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body className={inter.className}>
        <div className="container mx-auto">
          <Navbar>
            <div className="mx-auto flex items-center justify-between text-blue-gray-900">
              <Typography
                as="a"
                href="#"
                className="mr-4 cursor-pointer py-1.5 font-medium"
              >
                Material Tailwind
              </Typography>
              <div className="hidden lg:block">
                <ul className="mb-4 mt-2 flex flex-col gap-2 lg:mb-0 lg:mt-0 lg:flex-row lg:items-center lg:gap-6">
                  <Typography
                    as="li"
                    variant="small"
                    color="blue-gray"
                    className="p-1 font-normal"
                  >
                    <a href="#" className="flex items-center">
                      Pages
                    </a>
                  </Typography>
                  <Typography
                    as="li"
                    variant="small"
                    color="blue-gray"
                    className="p-1 font-normal"
                  >
                    <a href="#" className="flex items-center">
                      Account
                    </a>
                  </Typography>
                  <Typography
                    as="li"
                    variant="small"
                    color="blue-gray"
                    className="p-1 font-normal"
                  >
                    <a href="#" className="flex items-center">
                      Blocks
                    </a>
                  </Typography>
                  <Typography
                    as="li"
                    variant="small"
                    color="blue-gray"
                    className="p-1 font-normal"
                  >
                    <a href="#" className="flex items-center">
                      Docs
                    </a>
                  </Typography>
                </ul>
              </div>
              <Button
                variant="gradient"
                size="sm"
                className="hidden lg:inline-block"
              >
                <span>Buy Now</span>
              </Button>
            </div>
          </Navbar>
          {children}
        </div>
      </body>
    </html>
  );
}
